# 可以给出一系列路径，选出第一个可用路径设置
function(fi_set_install_prefix)
    foreach(path IN LISTS ARGV)
        if(NOT path)
            continue()
        endif()
        cmake_path(SET path NORMALIZE "${path}")
        cmake_path(IS_ABSOLUTE path is_vaild)
        if(is_vaild)
            message("安装位置: ${path}")
            # 因为在下层函数中，所以需要使用CACHE变量全局生效
            set(CMAKE_INSTALL_PREFIX "${path}" CACHE PATH "安装根路径" FORCE)
            return()
        endif()
    endforeach()
    message("给出的所有安装路径都不可用，将安装到系统路径${CMAKE_INSTALL_PREFIX}")
endfunction()
