function(fi_set_install_prefix)
    foreach(path IN LISTS ARGV)
        if(NOT path)
            continue()
        endif()
        cmake_path(SET path NORMALIZE "${path}")
        cmake_path(IS_ABSOLUTE path is_vaild)
        if(is_vaild)
            message("安装位置: ${path}")
            # 因为在下层函数中，所以需要使用CACHE变量全局生效
            set(CMAKE_INSTALL_PREFIX "${path}" CACHE PATH "安装根路径" FORCE)
            return()
        endif()
    endforeach()
endfunction()
